### ISSUE TITLE
RuntimeError: CUDA error: CUBLAS_STATUS_EXECUTION_FAILED

### ISSUE THREAD

**Issue by Elapsedf** [Derekabc/MARL_CAVs#50]
Thank you very much for opening up the repo! However, when I run the code "python run_mappo.py", it raise an error as below:
❯ python run_mappo.py
/data/shenzhen/anaconda3/envs/marl_cav/lib/python3.6/site-packages/torch/cuda/__init__.py:104: UserWarning: 
NVIDIA GeForce RTX 3090 with CUDA capability sm_86 is not compatible with the current PyTorch installation.
The current PyTorch install supports CUDA capabilities sm_37 sm_50 sm_60 sm_70 sm_75.
If you want to use the NVIDIA GeForce RTX 3090 GPU with PyTorch, please check the instructions at https://pytorch.org/get-started/locally/

  warnings.warn(incompatible_device_warn.format(device_name, capability, " ".join(arch_list), device_name))
ERROR:root:Can not find checkpoint for ./results/Jul_15_08_19_29/models/
Traceback (most recent call last):
  File "run_mappo.py", line 227, in <module>
    train(args)
  File "run_mappo.py", line 133, in train
    mappo.interact()
  File "/data/shenzhen/zdf/Highway/MARL_CAVs/MARL/MAPPO.py", line 113, in interact
    action = self.exploration_action(self.env_state, self.n_agents)
  File "/data/shenzhen/zdf/Highway/MARL_CAVs/MARL/MAPPO.py", line 219, in exploration_action
    softmax_actions = self._softmax_action(state, n_agents)
  File "/data/shenzhen/zdf/Highway/MARL_CAVs/MARL/MAPPO.py", line 209, in _softmax_action
    softmax_action_var = th.exp(self.actor(state_var[:, agent_id, :]))
  File "/data/shenzhen/zdf/Highway/MARL_CAVs/MARL/single_agent/Model_common.py", line 19, in __call__
    out = nn.functional.relu(self.fc1(state))
  File "/data/shenzhen/anaconda3/envs/marl_cav/lib/python3.6/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/data/shenzhen/anaconda3/envs/marl_cav/lib/python3.6/site-packages/torch/nn/modules/linear.py", line 93, in forward
    return F.linear(input, self.weight, self.bias)
  File "/data/shenzhen/anaconda3/envs/marl_cav/lib/python3.6/site-packages/torch/nn/functional.py", line 1690, in linear
    ret = torch.addmm(bias, input, weight.t())
RuntimeError: CUDA error: CUBLAS_STATUS_EXECUTION_FAILED when calling `cublasSgemm( handle, opa, opb, m, n, k, &alpha, a, lda, b, ldb, &beta, c, ldc)`

I have checked the closed issue and don't find the same solved issue. So I would appreciate it if you could help me :)

**Comment by Elapsedf** [comment]
Oh, I have solved it with this blog: https://blog.csdn.net/a563562675/article/details/121656894
I would closed the issue :)

**Comment by Elapsedf** [comment]
Oh, I have solved it with this blog: https://blog.csdn.net/a563562675/article/details/121656894
I would closed the issue :)
